/**
 * BacktestCharts.jsx
 * ----------------------------------------
 * Renders the three matplotlib/seaborn charts generated by the Python backend.
 * Each chart is a base64-encoded PNG — Python does all the statistical rendering.
 *
 * Props:
 *   charts  — { backtest_chart, width_distribution, volatility_chart } base64 PNGs
 *   metrics — { n_predictions, coverage_95, avg_width, mean_winkler_95 } from backtest
 */

import React, { useState } from "react";
import { ChevronDown, ChevronUp, BarChart2, Download, AlertCircle, Loader } from "lucide-react";

// ── Build chart metadata dynamically from real metrics ─────
function buildCharts(metrics) {
  const n       = metrics?.n_predictions;
  const cov     = metrics?.coverage_95;
  const width   = metrics?.avg_width;
  const hits    = n != null && cov != null ? Math.round(n * cov)       : null;
  const misses  = n != null && hits != null ? n - hits                  : null;
  const widthFmt = width != null ? `$${Math.round(width).toLocaleString()}` : "—";

  return [
    {
      key:         "backtest_chart",
      title:       "30-Day Walk-Forward: Actual vs 95% Predicted Range",
      description: n
        ? `${n} hourly BTC predictions. Green ribbon = 95% CI. Blue line = actual. Red dots = misses.`
        : "Hourly BTC predictions. Green ribbon = 95% CI. Blue line = actual. Red dots = misses.",
      defaultOpen: true,
      filename:    "btc_backtest_chart.png",
    },
    {
      key:         "width_distribution",
      title:       "Prediction Width Distribution (Hit / Miss)",
      description: hits != null
        ? `Histogram of interval widths. Green = hits (${hits}), Red = misses (${misses}). Avg width ≈ ${widthFmt}.`
        : `Histogram of interval widths. Green = hits, Red = misses. Avg width ≈ ${widthFmt}.`,
      defaultOpen: false,
      filename:    "btc_width_distribution.png",
    },
    {
      key:         "volatility_chart",
      title:       "Hourly Volatility (σ) — Clustering",
      description: "Rolling 20-bar hourly σ over the 30-day backtest. Clusters correspond to BTC price swings.",
      defaultOpen: false,
      filename:    "btc_volatility_chart.png",
    },
  ];
}

// ── Single collapsible chart panel ─────────────────────────
function ChartPanel({ title, description, src, defaultOpen, filename, loading }) {
  const [open, setOpen] = useState(defaultOpen);

  function handleDownload() {
    if (!src) return;
    const link = document.createElement("a");
    link.href     = `data:image/png;base64,${src}`;
    link.download = filename;
    link.click();
  }

  return (
    <div className="card overflow-hidden">
      {/* Header row — always visible */}
      <div className="flex items-center justify-between">
        <button
          className="flex items-center gap-2 text-left flex-1 min-w-0"
          onClick={() => setOpen(o => !o)}
          id={`chart-panel-${title.replace(/\s+/g, "-").toLowerCase().slice(0, 30)}`}
          aria-expanded={open}
        >
          <BarChart2 size={14} className="text-muted flex-shrink-0" />
          <span className="text-sm font-medium text-text truncate">{title}</span>
          {open
            ? <ChevronUp   size={14} className="text-muted flex-shrink-0 ml-auto mr-2" />
            : <ChevronDown size={14} className="text-muted flex-shrink-0 ml-auto mr-2" />}
        </button>

        {/* Download button — only when open and data available */}
        {open && src && (
          <button
            onClick={handleDownload}
            className="btn-ghost text-[11px] gap-1 flex-shrink-0"
            title={`Download ${filename}`}
          >
            <Download size={11} /> PNG
          </button>
        )}
      </div>

      {/* Expanded body */}
      {open && (
        <div className="mt-4">
          {/* Description */}
          <p className="text-[11px] text-muted mb-3">{description}</p>

          {/* Loading skeleton */}
          {loading && (
            <div className="h-40 flex flex-col items-center justify-center gap-2 text-muted rounded-lg border border-border">
              <Loader size={20} className="animate-spin" />
              <span className="text-xs">Generating chart…</span>
            </div>
          )}

          {/* Error state */}
          {!loading && !src && (
            <div className="h-32 flex flex-col items-center justify-center gap-2 text-muted rounded-lg border border-border">
              <AlertCircle size={18} className="text-yellow" />
              <span className="text-xs">Chart not available — run backtest first.</span>
              <code className="text-[10px] bg-surface px-2 py-0.5 rounded">
                POST /api/run-backtest
              </code>
            </div>
          )}

          {/* Chart image — lazy loaded only when panel is open */}
          {!loading && src && (
            <img
              src={`data:image/png;base64,${src}`}
              alt={description}
              className="w-full rounded-lg border border-border"
              loading="lazy"
              decoding="async"
            />
          )}
        </div>
      )}
    </div>
  );
}

// ── Main export ────────────────────────────────────────────
export default function BacktestCharts({ charts, metrics }) {
  // `charts` is null while loading, {} if error, {backtest_chart, ...} if ready
  const isLoading = charts === null;
  const isError   = charts !== null && !charts?.backtest_chart;

  const chartConfigs = buildCharts(metrics);
  const n = metrics?.n_predictions;

  return (
    <div className="flex flex-col gap-3">
      {/* Section header */}
      <div className="flex items-center justify-between">
        <p className="section-title mb-0">Backtest Analysis — matplotlib + seaborn</p>
        {!isLoading && !isError && n && (
          <span className="text-[10px] text-muted">
            {n} predictions · 30-day walk-forward · no-peek enforced
          </span>
        )}
      </div>

      {/* Top-level error (entire charts endpoint failed) */}
      {isError && (
        <div className="card flex items-center gap-3 text-sm text-muted">
          <AlertCircle size={16} className="text-yellow flex-shrink-0" />
          <span>
            Chart data unavailable. Run&nbsp;
            <code className="font-mono text-xs bg-surface px-1.5 py-0.5 rounded">
              POST /api/run-backtest
            </code>
            &nbsp;then refresh.
          </span>
        </div>
      )}

      {/* Chart panels */}
      {chartConfigs.map(cfg => (
        <ChartPanel
          key={cfg.key}
          title={cfg.title}
          description={cfg.description}
          src={charts?.[cfg.key] ?? null}
          defaultOpen={cfg.defaultOpen}
          filename={cfg.filename}
          loading={isLoading}
        />
      ))}
    </div>
  );
}
