/**
 * BacktestCharts.jsx
 * ------------------
 * Renders the three matplotlib/seaborn charts generated by Python
 * as base64-encoded PNG images. No SVG needed — Python does the heavy lifting.
 */

import React, { useState } from "react";
import { ChevronDown, ChevronUp, BarChart } from "lucide-react";

function ChartPanel({ title, src, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="card overflow-hidden">
      <button
        className="w-full flex items-center justify-between text-left"
        onClick={() => setOpen(o => !o)}
        id={`chart-panel-${title.replace(/\s+/g, "-").toLowerCase()}`}
      >
        <div className="flex items-center gap-2">
          <BarChart size={15} className="text-muted" />
          <span className="text-sm font-medium text-text">{title}</span>
        </div>
        {open
          ? <ChevronUp size={15} className="text-muted" />
          : <ChevronDown size={15} className="text-muted" />}
      </button>

      {open && (
        <div className="mt-4">
          {src
            ? <img
                src={`data:image/png;base64,${src}`}
                alt={title}
                className="w-full rounded-lg border border-border"
              />
            : <div className="h-32 flex items-center justify-center text-muted text-sm">
                Chart not available — run backtest first.
              </div>
          }
        </div>
      )}
    </div>
  );
}

export default function BacktestCharts({ charts }) {
  return (
    <div className="flex flex-col gap-3">
      <p className="section-title">Backtest Analysis (matplotlib + seaborn)</p>
      <ChartPanel
        title="30-Day Walk-Forward: Actual vs 95% Predicted Range"
        src={charts?.backtest_chart}
        defaultOpen={true}
      />
      <ChartPanel
        title="Prediction Width Distribution (Hit / Miss)"
        src={charts?.width_distribution}
      />
      <ChartPanel
        title="Hourly Volatility (σ) — Clustering"
        src={charts?.volatility_chart}
      />
    </div>
  );
}
